/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_labyrinthe;

import java.awt.Color;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JButton;
import javax.swing.JFrame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import java.net.URL;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @authors Owen HAYET, Raphael MARTY, Oscar HUNAUT, Paul MACZKOWIAK
 */
public class Accueil extends javax.swing.JFrame {
    /**
     * Creates new form Accueil
     */
   
    public Accueil() {
        Partie Session;
        initComponents();
            TEXTNOM2.setVisible(false);
            Lab3.setVisible(false);
            TEXTNOM3.setVisible(false);
            Lab5.setVisible(false);
            TEXTNOM4.setVisible(false);
            Lab7.setVisible(false);
       
            Spinner.addChangeListener(new ChangeListener(){
            @Override
            public void stateChanged(ChangeEvent e) {
            int P = (int) Spinner.getValue();
            if ((int) Spinner.getValue()==1){
            TEXTNOM1.setVisible(true);
            Lab1.setVisible(true);
            TEXTNOM2.setVisible(false);
            Lab3.setVisible(false);
            TEXTNOM3.setVisible(false);
            Lab5.setVisible(false);
            TEXTNOM4.setVisible(false);
            Lab7.setVisible(false);
        } else if (P==2){
            TEXTNOM1.setVisible(true);
            Lab1.setVisible(true);
            TEXTNOM2.setVisible(true);
            Lab3.setVisible(true);
            TEXTNOM3.setVisible(false);
            Lab5.setVisible(false);
            TEXTNOM4.setVisible(false);
            Lab7.setVisible(false);
        } else if (P==3){
            TEXTNOM1.setVisible(true);
            Lab1.setVisible(true);
            TEXTNOM2.setVisible(true);
            Lab3.setVisible(true);
            TEXTNOM3.setVisible(true);
            Lab5.setVisible(true);
            TEXTNOM4.setVisible(false);
            Lab7.setVisible(false);
        } else if (P==4){
            TEXTNOM1.setVisible(true);
            Lab1.setVisible(true);
            TEXTNOM2.setVisible(true);
            Lab3.setVisible(true);
            TEXTNOM3.setVisible(true);
            Lab5.setVisible(true);
            TEXTNOM4.setVisible(true);
            Lab7.setVisible(true);

       
        }
        if (P==1){
            String Nom1 = TEXTNOM1.getText();  
        } else if (P==2){
            String Nom1 = TEXTNOM1.getText();
            String Nom2 = TEXTNOM2.getText();
        } else if (P==3){
            String Nom1 = TEXTNOM1.getText();
            String Nom2 = TEXTNOM2.getText();
            String Nom3 = TEXTNOM1.getText();
        } else if (P==4){
            String Nom1 = TEXTNOM1.getText();
            String Nom2 = TEXTNOM2.getText();
            String Nom3 = TEXTNOM1.getText();
            String Nom4 = TEXTNOM1.getText();
        }}
            });
           
           
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        PAN1 = new javax.swing.JPanel();
        Lancer = new javax.swing.JToggleButton();
        Spinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text1 = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        Lab3 = new javax.swing.JLabel();
        TEXTNOM2 = new javax.swing.JTextField();
        Lab5 = new javax.swing.JLabel();
        TEXTNOM3 = new javax.swing.JTextField();
        TEXTNOM1 = new javax.swing.JTextField();
        Lab7 = new javax.swing.JLabel();
        TEXTNOM4 = new javax.swing.JTextField();
        Quitter = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        DuSON = new javax.swing.JButton();
        PasDuSON = new javax.swing.JButton();
        Fond = new javax.swing.JLabel();
        DuSON.setVisible(false);
        PasDuSON.setVisible(true);
        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PAN1.setBackground(new java.awt.Color(0, 0, 51));

        Lancer.setBackground(new java.awt.Color(0, 153, 0));
        Lancer.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        Lancer.setForeground(new java.awt.Color(0, 0, 0));
        Lancer.setText("Lancer");
        Lancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LancerActionPerformed(evt);
            }
        });

        Spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        Spinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Spinner.setName(""); // NOI18N

        Text1.setBackground(new java.awt.Color(0, 0, 102));
        Text1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Text1.setText("Nombre de Joueurs");
        Text1.setForeground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setViewportView(Text1);

        Lab1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        Lab1.setText("Nom du premier Joueur ");
        Lab1.setForeground(Color.white);

        Lab3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        Lab3.setText("Nom du deuxieme Joueur ");
        Lab3.setForeground(Color.white);

        TEXTNOM2.setBackground(new java.awt.Color(51, 0, 102));
        TEXTNOM2.setText("Nom");
        TEXTNOM2.setForeground(Color.white);

        Lab5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        Lab5.setText("Nom du troisieme Joueur ");
        Lab5.setForeground(Color.white);

        TEXTNOM3.setBackground(new java.awt.Color(51, 0, 102));
        TEXTNOM3.setText("Nom");
        TEXTNOM3.setForeground(Color.white);

        TEXTNOM1.setBackground(new java.awt.Color(51, 0, 102));
        TEXTNOM1.setText("Nom");
        TEXTNOM1.setForeground(Color.white);

        Lab7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        Lab7.setText("Nom du quatrieme Joueur ");
        Lab7.setForeground(Color.white);

        TEXTNOM4.setBackground(new java.awt.Color(51, 0, 102));
        TEXTNOM4.setText("Nom");
        TEXTNOM4.setForeground(Color.white);

        Quitter.setBackground(new java.awt.Color(255, 0, 0));
        Quitter.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        Quitter.setForeground(new java.awt.Color(0, 0, 0));
        Quitter.setText("Quitter");
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });

        jLabel1.setText("");

        javax.swing.GroupLayout PAN1Layout = new javax.swing.GroupLayout(PAN1);
        PAN1.setLayout(PAN1Layout);
        PAN1Layout.setHorizontalGroup(
            PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAN1Layout.createSequentialGroup()
                .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAN1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Quitter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(Lancer))
                    .addGroup(PAN1Layout.createSequentialGroup()
                        .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PAN1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PAN1Layout.createSequentialGroup()
                                        .addComponent(Lab3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TEXTNOM2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PAN1Layout.createSequentialGroup()
                                        .addComponent(Lab5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TEXTNOM3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PAN1Layout.createSequentialGroup()
                                        .addComponent(Lab7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TEXTNOM4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PAN1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PAN1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Lab1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TEXTNOM1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAN1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(186, 186, 186))
        );
        PAN1Layout.setVerticalGroup(
            PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAN1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Spinner)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lab1)
                    .addComponent(TEXTNOM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lab3)
                    .addComponent(TEXTNOM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXTNOM3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lab5))
                .addGap(30, 30, 30)
                .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lab7)
                    .addComponent(TEXTNOM4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PAN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lancer)
                    .addComponent(Quitter))
                .addContainerGap())
        );

        getContentPane().add(PAN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 420, 360));

        DuSON.setBackground(new java.awt.Color(51, 0, 102));
        DuSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/du-son.png"))); // NOI18N
        DuSON.setVisible(false);
        DuSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuSONActionPerformed(evt);
            }
        });
        getContentPane().add(DuSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        PasDuSON.setBackground(new java.awt.Color(51, 0, 102));
        PasDuSON.setVisible(false);
        PasDuSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pas-de-son.png"))); // NOI18N
        PasDuSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasDuSONActionPerformed(evt);
            }
        });
        getContentPane().add(PasDuSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));
        PasDuSON.setVisible(true);
        Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/5008c241263635.579f73a622fe3.gif"))); // NOI18N

        getContentPane().add(Fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));
        playSound("src/Music/otherside.wav");
        pack();
    }// </editor-fold>                        

    private void LancerActionPerformed(java.awt.event.ActionEvent evt) {
        stopSound();
        int nb = (int) Spinner.getValue();
        String Nom1 = TEXTNOM1.getText();
        String Nom2 = TEXTNOM2.getText();
        String Nom3 = TEXTNOM3.getText();
        String Nom4 = TEXTNOM4.getText();
        this.dispose();
        new Interface(nb, Nom1, Nom2, Nom3, Nom4).setVisible(true);

    }                                      

    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {                                        
        this.dispose();
    }                                      

    private Clip clip;  // Declare Clip as a class member

private void PasDuSONActionPerformed(java.awt.event.ActionEvent evt) {                                        
    // Stop the music
    stopSound();
    DuSON.setVisible(true);
    PasDuSON.setVisible(false);
}                                        

private void DuSONActionPerformed(java.awt.event.ActionEvent evt) {                                      
    // Play the music
    playSound("src/Music/otherside.wav");  // Replace with the actual path to your music file
    PasDuSON.setVisible(true);
    DuSON.setVisible(false);
}

// Method to play the sound
private void playSound(String filePath) {
    try {
        File file = new File(filePath);
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
        clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch (IOException | LineUnavailableException | UnsupportedAudioFileException e) {
        e.printStackTrace();
    }
}

// Method to stop the sound
private void stopSound() {
    if (clip != null && clip.isRunning()) {
        clip.stop();
        clip.close();
    }
}                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                    
    private javax.swing.JButton DuSON;
    private javax.swing.JLabel Fond;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab3;
    private javax.swing.JLabel Lab5;
    private javax.swing.JLabel Lab7;
    protected javax.swing.JToggleButton Lancer;
    private javax.swing.JPanel PAN1;
    private javax.swing.JButton PasDuSON;
    private javax.swing.JToggleButton Quitter;
    private javax.swing.JSpinner Spinner;
    private javax.swing.JTextField TEXTNOM1;
    private javax.swing.JTextField TEXTNOM2;
    private javax.swing.JTextField TEXTNOM3;
    private javax.swing.JTextField TEXTNOM4;
    private javax.swing.JLabel Text1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                  
}

