/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package projet_labyrinthe;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import static projet_labyrinthe.Interface.ScreenDim;

/**
 *
 * @authors Owen HAYET, Raphael MARTY, Oscar HUNAUT, Paul MACZKOWIAK
 */
public class Chrono {
    public Timer t1 = new Timer(10, new Check(1));
    public Timer t2 = new Timer(10, new Check(2));
    public Timer t3 = new Timer(10, new Check(3));
    public Timer t4 = new Timer(10, new Check(4));
   
    public boolean isTimer1Running = false;
    public boolean isTimer2Running = false;
    public boolean isTimer3Running = false;
    public boolean isTimer4Running = false;
    
    
     /**
     * Creer les chrono des joueurs
     */
    public Chrono(JPanel pane) {
        initComponents(pane);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(JPanel pane) {

        Chrono_J1 = new javax.swing.JPanel();
        LabelMinutes1 = new javax.swing.JLabel();
        jLabelpoints = new javax.swing.JLabel();
        LabelSEC1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelmS1 = new javax.swing.JLabel();
        Chrono_J2 = new javax.swing.JPanel();
        LabelmS2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelSEC2 = new javax.swing.JLabel();
        LabelMinutes2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        Chrono_J3 = new javax.swing.JPanel();
        LabelmS3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelSEC3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelMinutes3 = new javax.swing.JLabel();
        Chrono_J4 = new javax.swing.JPanel();
        LabelmS4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LabelSEC4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabelMinutes4 = new javax.swing.JLabel();



        Chrono_J1.setBackground(new java.awt.Color(0,102,153));

        LabelMinutes1.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelMinutes1.setText("00");

        jLabelpoints.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabelpoints.setText(":");

        LabelSEC1.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelSEC1.setText("00");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel2.setText(":");

        LabelmS1.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelmS1.setText("00");

        javax.swing.GroupLayout Chrono_J1Layout = new javax.swing.GroupLayout(Chrono_J1);
        Chrono_J1.setLayout(Chrono_J1Layout);
        Chrono_J1Layout.setHorizontalGroup(
            Chrono_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
            .addGroup(Chrono_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Chrono_J1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LabelMinutes1)
                    .addGap(6, 6, 6)
                    .addComponent(jLabelpoints)
                    .addGap(6, 6, 6)
                    .addComponent(LabelSEC1)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel2)
                    .addGap(6, 6, 6)
                    .addComponent(LabelmS1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Chrono_J1Layout.setVerticalGroup(
            Chrono_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(Chrono_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Chrono_J1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(Chrono_J1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelMinutes1)
                        .addComponent(jLabelpoints)
                        .addComponent(LabelSEC1)
                        .addComponent(jLabel2)
                        .addComponent(LabelmS1))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pane.add(Chrono_J1, new AbsoluteConstraints((ScreenDim.width) * 22 / 100, (ScreenDim.height) * 103 / 200,100,17));

        Chrono_J2.setBackground(new java.awt.Color(0, 153, 51));

        LabelmS2.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelmS2.setText("00");

        jLabel4.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel4.setText(":");

        LabelSEC2.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelSEC2.setText("00");

        LabelMinutes2.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelMinutes2.setText("00");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel3.setText(":");

        javax.swing.GroupLayout Chrono_J2Layout = new javax.swing.GroupLayout(Chrono_J2);
        Chrono_J2.setLayout(Chrono_J2Layout);
        Chrono_J2Layout.setHorizontalGroup(
            Chrono_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
            .addGroup(Chrono_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Chrono_J2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LabelMinutes2)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel3)
                    .addGap(6, 6, 6)
                    .addComponent(LabelSEC2)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel4)
                    .addGap(6, 6, 6)
                    .addComponent(LabelmS2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Chrono_J2Layout.setVerticalGroup(
            Chrono_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(Chrono_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Chrono_J2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(Chrono_J2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelMinutes2)
                        .addComponent(jLabel3)
                        .addComponent(LabelSEC2)
                        .addComponent(jLabel4)
                        .addComponent(LabelmS2))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pane.add(Chrono_J2, new org.netbeans.lib.awtextra.AbsoluteConstraints((ScreenDim.width) * 22 / 100, (ScreenDim.height) * 123 / 200, 100, 17));

        
        Chrono_J3.setBackground(new java.awt.Color(153, 0,0));

        LabelmS3.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelmS3.setText("00");

        jLabel6.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel6.setText(":");

        LabelSEC3.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelSEC3.setText("00");

        jLabel5.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel5.setText(":");

        LabelMinutes3.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelMinutes3.setText("00");

        javax.swing.GroupLayout Chrono_J3Layout = new javax.swing.GroupLayout(Chrono_J3);
        Chrono_J3.setLayout(Chrono_J3Layout);
        Chrono_J3Layout.setHorizontalGroup(
            Chrono_J3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
            .addGroup(Chrono_J3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Chrono_J3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LabelMinutes3)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel5)
                    .addGap(6, 6, 6)
                    .addComponent(LabelSEC3)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel6)
                    .addGap(6, 6, 6)
                    .addComponent(LabelmS3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Chrono_J3Layout.setVerticalGroup(
            Chrono_J3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(Chrono_J3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Chrono_J3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(Chrono_J3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelMinutes3)
                        .addComponent(jLabel5)
                        .addComponent(LabelSEC3)
                        .addComponent(jLabel6)
                        .addComponent(LabelmS3))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pane.add(Chrono_J3, new org.netbeans.lib.awtextra.AbsoluteConstraints((ScreenDim.width) * 22 / 100, (ScreenDim.height) * 143 /200, 100, 17));

        Chrono_J4.setBackground(new java.awt.Color(200, 200, 0));

        LabelmS4.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelmS4.setText("00");

        jLabel8.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel8.setText(":");

        LabelSEC4.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelSEC4.setText("00");

        jLabel7.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jLabel7.setText(":");

        LabelMinutes4.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        LabelMinutes4.setText("00");

        javax.swing.GroupLayout Chrono_J4Layout = new javax.swing.GroupLayout(Chrono_J4);
        Chrono_J4.setLayout(Chrono_J4Layout);
        Chrono_J4Layout.setHorizontalGroup(
            Chrono_J4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
            .addGroup(Chrono_J4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Chrono_J4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LabelMinutes4)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel7)
                    .addGap(6, 6, 6)
                    .addComponent(LabelSEC4)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel8)
                    .addGap(6, 6, 6)
                    .addComponent(LabelmS4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Chrono_J4Layout.setVerticalGroup(
            Chrono_J4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(Chrono_J4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Chrono_J4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(Chrono_J4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LabelMinutes4)
                        .addComponent(jLabel7)
                        .addComponent(LabelSEC4)
                        .addComponent(jLabel8)
                        .addComponent(LabelmS4))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pane.add(Chrono_J4, new org.netbeans.lib.awtextra.AbsoluteConstraints((ScreenDim.width) * 22 / 100, (ScreenDim.height) * 163 /200, 100, 17));

    }// </editor-fold>                        

    
class Check implements ActionListener {
        private final int player;
        private int localMs = 0;
        private int localSec = 0;
        private int localMin = 0;

        public Check(int player) {
            this.player = player;
        }
        
        @Override
    public void actionPerformed(ActionEvent e) {
        localMs += 1;
        if (localMs == 100) {
            localSec += 1;
            localMs = 0;
        }
        if (localSec == 60) {
            localMin += 1;
            localSec = 0;
        }

        updateLabels(player, localMin, localSec, localMs);
    }

    }
    
private void updateLabels(int player, int min, int sec, int ms) {
    switch (player) {
        case 1 -> {
            LabelMinutes1.setText(String.format("%02d", min));
            LabelSEC1.setText(String.format("%02d", sec));
            LabelmS1.setText(String.format("%02d", ms));
            }
        case 2 -> {
            LabelMinutes2.setText(String.format("%02d", min));
            LabelSEC2.setText(String.format("%02d", sec));
            LabelmS2.setText(String.format("%02d", ms));
            }
        case 3 -> {
            LabelMinutes3.setText(String.format("%02d", min));
            LabelSEC3.setText(String.format("%02d", sec));
            LabelmS3.setText(String.format("%02d", ms));
            }
        case 4 -> {
            LabelMinutes4.setText(String.format("%02d", min));
            LabelSEC4.setText(String.format("%02d", sec));
            LabelmS4.setText(String.format("%02d", ms));
            }
    }
}

    /**
     * Lance un chrono
     * @param player le joueur dont le chrono doit etre affecte
     */
    public void start (int player) {
    if (player == 0 && !isTimer1Running) {
        t1.start();
        isTimer1Running=true;
    } else if (player == 1 && !isTimer2Running) {
            t2.start();
            isTimer2Running = true;
    } else if (player == 2 && !isTimer3Running) {
        t3.start();
        isTimer3Running=true;
    } else if (player == 3 && !isTimer4Running) {
        t4.start();
        isTimer4Running=true;
    }
}

    /**
     * Arrete un chrono
     * @param player le joueur dont le chrono doit etre affecte
     */
    public void stop(int player) {
    if (player == 0) {
            t1.stop();
            isTimer1Running = false;
        } else if (player == 1) {
            t2.stop();
            isTimer2Running = false;
        } else if (player == 2) {
            t3.stop();
            isTimer3Running = false;
        } else if (player == 3) {
            t4.stop();
            isTimer4Running = false;
        }

}
                                                                  

// Variables declaration - do not modify                     
    public javax.swing.JPanel Chrono_J1;
    public javax.swing.JPanel Chrono_J2;
    public javax.swing.JPanel Chrono_J3;
    public javax.swing.JPanel Chrono_J4;
    private javax.swing.JLabel LabelMinutes1;
    private javax.swing.JLabel LabelMinutes2;
    private javax.swing.JLabel LabelMinutes3;
    private javax.swing.JLabel LabelMinutes4;
    private javax.swing.JLabel LabelSEC1;
    private javax.swing.JLabel LabelSEC2;
    private javax.swing.JLabel LabelSEC3;
    private javax.swing.JLabel LabelSEC4;
    private javax.swing.JLabel LabelmS1;
    private javax.swing.JLabel LabelmS2;
    private javax.swing.JLabel LabelmS3;
    private javax.swing.JLabel LabelmS4;
    private javax.swing.JButton Start1;
    private javax.swing.JButton Start2;
    private javax.swing.JButton Start3;
    private javax.swing.JButton Start4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelpoints;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration   
}
