/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_labyrinthe;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import  javax.swing.Timer;


/**
 *
 * @author marty
 */
public class chrono_interface extends javax.swing.JFrame {
    public Timer t1 = new Timer(10, new Check(1));
    public Timer t2 = new Timer(10, new Check(2));
    public Timer t3 = new Timer(10, new Check(3));
    public Timer t4 = new Timer(10, new Check(4));
   
    public boolean isTimer1Running = false;
    public boolean isTimer2Running = false;
    public boolean isTimer3Running = false;
    public boolean isTimer4Running = false;
    
    
   

    /**
     * Creates new form chrono_interface
     */
    public chrono_interface() {
        initComponents();
    }
    

        
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelmS1 = new javax.swing.JLabel();
        jLabelpoints = new javax.swing.JLabel();
        LabelMinutes1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelSEC1 = new javax.swing.JLabel();
        Start1 = new javax.swing.JButton();
        LabelMinutes2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelSEC2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelmS2 = new javax.swing.JLabel();
        Start2 = new javax.swing.JButton();
        LabelMinutes3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LabelSEC3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelmS3 = new javax.swing.JLabel();
        Start3 = new javax.swing.JButton();
        LabelMinutes4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LabelSEC4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LabelmS4 = new javax.swing.JLabel();
        Start4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelmS1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelmS1.setText("00");

        jLabelpoints.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabelpoints.setText(":");

        LabelMinutes1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelMinutes1.setText("00");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel2.setText(":");

        LabelSEC1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelSEC1.setText("00");

        Start1.setText("Start J1");
        Start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start1ActionPerformed(evt);
            }
        });

        LabelMinutes2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelMinutes2.setText("00");

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel3.setText(":");

        LabelSEC2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelSEC2.setText("00");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel4.setText(":");

        LabelmS2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelmS2.setText("00");

        Start2.setText("Start J2");
        Start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start2ActionPerformed(evt);
            }
        });

        LabelMinutes3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelMinutes3.setText("00");

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel5.setText(":");

        LabelSEC3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelSEC3.setText("00");

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel6.setText(":");

        LabelmS3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelmS3.setText("00");

        Start3.setText("Start J3");
        Start3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start3ActionPerformed(evt);
            }
        });

        LabelMinutes4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelMinutes4.setText("00");

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel7.setText(":");

        LabelSEC4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelSEC4.setText("00");

        jLabel8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel8.setText(":");

        LabelmS4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        LabelmS4.setText("00");

        Start4.setText("Start J4");
        Start4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Start4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelMinutes4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelSEC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelmS4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Start3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelMinutes3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelSEC4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelmS3))
                            .addComponent(Start2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelMinutes2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelSEC3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelmS2))
                            .addComponent(Start1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelMinutes1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelpoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelSEC1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelmS1)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelpoints)
                    .addComponent(LabelMinutes1)
                    .addComponent(jLabel2)
                    .addComponent(LabelSEC1)
                    .addComponent(LabelmS1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Start1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMinutes2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(LabelSEC3)
                    .addComponent(LabelmS2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Start2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(LabelmS3)
                    .addComponent(LabelMinutes3)
                    .addComponent(LabelSEC4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Start3)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMinutes4)
                    .addComponent(jLabel7)
                    .addComponent(LabelSEC2)
                    .addComponent(jLabel8)
                    .addComponent(LabelmS4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Start4)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
class Check implements ActionListener {
        private final int player;
        private int localMs = 0;
        private int localSec = 0;
        private int localMin = 0;

        public Check(int player) {
            this.player = player;
        }
        
        @Override
    public void actionPerformed(ActionEvent e) {
        localMs += 1;
        if (localMs == 100) {
            localSec += 1;
            localMs = 0;
        }
        if (localSec == 60) {
            localMin += 1;
            localSec = 0;
        }

        updateLabels(player, localMin, localSec, localMs);
    }

    }
    
private void updateLabels(int player, int min, int sec, int ms) {
    switch (player) {
        case 1:
            LabelMinutes1.setText(String.format("%02d", min));
            LabelSEC1.setText(String.format("%02d", sec));
            LabelmS1.setText(String.format("%02d", ms));
            break;
        case 2:
            LabelMinutes2.setText(String.format("%02d", min));
            LabelSEC2.setText(String.format("%02d", sec));
            LabelmS2.setText(String.format("%02d", ms));
            break;
        case 3:
            LabelMinutes3.setText(String.format("%02d", min));
            LabelSEC3.setText(String.format("%02d", sec));
            LabelmS3.setText(String.format("%02d", ms));
            break;
        case 4:
            LabelMinutes4.setText(String.format("%02d", min));
            LabelSEC4.setText(String.format("%02d", sec));
            LabelmS4.setText(String.format("%02d", ms));
            break;
    }
}


private void start (JButton btn) {
    if (btn == Start1 && !isTimer1Running) {
        t1.start();
        isTimer1Running=true;
    } else if (btn == Start2 && !isTimer2Running) {
            t2.start();
            isTimer2Running = true;
    } else if (btn == Start3 && !isTimer3Running) {
        t3.start();
        isTimer3Running=true;
    } else if (btn == Start4 && !isTimer4Running) {
        t4.start();
        isTimer4Running=true;
    }
}
private void stop(JButton btn) {
    if (btn == Start1) {
            t1.stop();
            isTimer1Running = false;
        } else if (btn == Start2) {
            t2.stop();
            isTimer2Running = false;
        } else if (btn == Start3) {
            t3.stop();
            isTimer3Running = false;
        } else if (btn == Start4) {
            t4.stop();
            isTimer4Running = false;
        }

}
        

    





    private void Start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start1ActionPerformed
        if (Start1.getText().equals("Start J1")) {
            Start1.setText("Stop1");
            
           start(Start1);
    }else { 
              Start1.setText( "Start J1");
        
            stop(Start1);
        }

        
    }//GEN-LAST:event_Start1ActionPerformed

    private void Start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start2ActionPerformed
        if (Start2.getText().equals("Start J2")) {
            Start2.setText("Stop2");
            start(Start2);
            
    }else { 
              Start2.setText( "Start J2");
        stop(Start2);

}
    }//GEN-LAST:event_Start2ActionPerformed

    private void Start3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start3ActionPerformed
       if (Start3.getText().equals("Start J3")) {
            Start3.setText("Stop3");
            start(Start3);
    }else { 
              Start3.setText( "Start J3");
        stop(Start3);

}
    }//GEN-LAST:event_Start3ActionPerformed

    private void Start4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start4ActionPerformed
       if (Start4.getText().equals("Start J4")) {
            Start4.setText("Stop4");
            start(Start4);
    }else { 
              Start4.setText( "Start J4");
              stop(Start4);

}
    }//GEN-LAST:event_Start4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chrono_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chrono_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chrono_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chrono_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chrono_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMinutes1;
    private javax.swing.JLabel LabelMinutes2;
    private javax.swing.JLabel LabelMinutes3;
    private javax.swing.JLabel LabelMinutes4;
    private javax.swing.JLabel LabelSEC1;
    private javax.swing.JLabel LabelSEC2;
    private javax.swing.JLabel LabelSEC3;
    private javax.swing.JLabel LabelSEC4;
    private javax.swing.JLabel LabelmS1;
    private javax.swing.JLabel LabelmS2;
    private javax.swing.JLabel LabelmS3;
    private javax.swing.JLabel LabelmS4;
    private javax.swing.JButton Start1;
    private javax.swing.JButton Start2;
    private javax.swing.JButton Start3;
    private javax.swing.JButton Start4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelpoints;
    // End of variables declaration//GEN-END:variables
}